server:
  port: 8080
spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
        url: jdbc:mysql://rew.mysql.database.azure.com:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: asdfgzxcvb10086
        password: "!68001bvc"
#         url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#         username: root
#         password: zhb22153753
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

      exclude: WEB-INF/**
logging:
  level:
    com.tkmybaitsdemo.demo: debug

